version: '3.3'
services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      ## Docker volume 설정을 할 경로 지정
      - /home/ubuntu/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-webserver
